Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "10.100.198.110"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.define "vm-host" do |d|
    d.vm.box = "centos/7"
    d.vm.network "private_network", ip: "10.100.198.130"

    d.vm.provision :shell, path: "scripts/bootstrap_ansible.sh"
    d.vm.provision :shell,
                   inline: 'PYTHONUNBUFFERED=1 ansible-playbook -vvv  \
            /vagrant/ansible/vm-host.yml -c local'
    d.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box
  end
end